# Generated by Django 5.2.3 on 2025-06-20 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='femaleactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='maleactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='multiplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('1', 'Ahmedabad'), ('2', 'Surat'), ('3', 'Vadodra'), ('4', 'Rajkot'), ('5', 'Morbi'), ('6', 'Anand'), ('7', 'Valsad')], max_length=30)),
                ('state', models.CharField(choices=[('1', 'Gujarat'), ('2', 'Maharastra'), ('3', 'Goa'), ('4', 'Rajeshthan'), ('5', 'TamilNadu')], max_length=30)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedata.maleactor')),
                ('actress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedata.femaleactor')),
                ('moviecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedata.category')),
            ],
        ),
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('1', '2D'), ('2', '3D'), ('3', '4DX3D')], max_length=30)),
                ('language', models.CharField(choices=[('1', 'Hindi'), ('2', 'English'), ('3', 'Gujarati'), ('4', 'Hinglish')], max_length=30)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedata.movie')),
                ('multiplexname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedata.multiplex')),
            ],
        ),
    ]
